
# Login

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "max2@gmail.com",
  "password": "max2"
}


### Transaction requests
###
GET http://localhost:3000/transactions/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5Njk3fQ.Iyq5AYBE8Yf_bcsqrslVtHZwLqQWRMHt18sivfHzmj8


###
GET http://localhost:3000/transactions/1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5Njk3fQ.Iyq5AYBE8Yf_bcsqrslVtHZwLqQWRMHt18sivfHzmj8



###
## type : can be a payment or a refund
POST http://localhost:3000/transactions
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4

{
  "amount": 20,
  "description": "description",
  "currency": "€",
  "client_first_name": "Toto",
  "client_last_name": "Dau",
  "client_email": "max@test.fr",
  "type": "payment"
}


###
DELETE http://localhost:3000/transactions/1

###
PUT http://localhost:3000/transactions/2
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4

{
  "currency": "$",
  "description": "Change MONEY"
}


### Merchant requests
###
GET http://localhost:3000/merchants/

###
POST http://localhost:3000/merchants/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4

{
  "companyName": "name of the company",
  "KBIS": "kbis value",
  "firstName": "john",
  "lastName": "max@test.fr",
  "email": "john@email.com",
  "address": "12 rue somewhere",
  "phone": "0788565289",
  "confirmationUrl": "confirmation url",
  "cancellationUrl": " cancelation url",
  "currency": "euro",
  "notificationUrl": "notification url"
}


###
PUT http://localhost:3000/merchants/3
Content-Type: application/json

{
  "currency": "$",
  "description": "Change currency"
}


###
DELETE http://localhost:3000/merchants/1

# Credentials requests

# Merchant requests

###
GET http://localhost:3000/credentials/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4

###
POST http://localhost:3000/credentials/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4

{
  "clientToken": "the token ",
  "clientSecret": "shhhhh ;)"
}


###
PUT http://localhost:3000/credentials/3
Content-Type: application/json

{
  "clientToken": "the token ",
  "clientSecret": "shhhhh ;)"
}


###
DELETE http://localhost:3000/credentials/1

# History requests
###

GET http://localhost:3000/history/

###

GET http://localhost:3000/history/1

###

POST http://localhost:3000/history
Content-Type: application/json

{
  "transaction_id": 1,
  "status": "created",
  "date": "2021-11-17T08:26:53"
}

###

DELETE http://localhost:3000/history/1

# Operation requests

###
GET http://localhost:3000/operation/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4


###
GET http://localhost:3000/operation/35

###
POST http://localhost:3000/operation
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4

{
  "type": "CAPTURED",
  "amount": 50,
  "status": "CREATED",
  "date": "2021-11-17T08:26:53",
  "transactionId": 2
}

###
DELETE http://localhost:3000/operation/1


###
PUT http://localhost:3000/operation/31
Content-Type: application/json

{
  "status":"PENDING"
}

# User requests

###
GET http://localhost:3000/user/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4


###
GET http://localhost:3000/user/1

###
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "max2@gmail.com",
  "password": "max2",
  "firstName": "max",
  "lastName": "dd",
  "role": "user"
}


###
DELETE http://localhost:3000/user/1


###
PUT http://localhost:3000/user/1
Content-Type: application/json

{
  "email":"test1@test.com"
}

