
# Login / Register

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "max4@gmail.com",
  "password": "max4"
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "max4@gmail.com",
  "password": "max4",
  "firstName": "max",
  "lastName": "dd",
  "merchantId":"2"
}


###With Token


### Transaction All
### User : only same MarchandId
### Admin : all
GET http://localhost:3000/transactions/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU


### Transaction Id
### User : only same MarchandId
### Admin : all
GET http://localhost:3000/transactions/2
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU


### Transaction Create
## type : can be a payment or a refund
POST http://localhost:3000/transactions
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4

{
  "amount": 20,
  "description": "description",
  "currency": "€",
  "client_first_name": "Toto",
  "client_last_name": "Dau",
  "client_email": "max@test.fr",
  "type": "payment"
}


### Transaction DELETE
DELETE http://localhost:3000/transactions/1

### Transaction PUT
PUT http://localhost:3000/transactions/2
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU

{
  "description": "Change MONEY",
  "currency": "€€€"
}


### Merchant requests

### Merchant All
### User : Not access
### Admin : Access
GET http://localhost:3000/merchants/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU



### Merchant Id
### User : Only MarchandId
### Admin : All
GET http://localhost:3000/merchants/1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU


###
POST http://localhost:3000/merchants/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4

{
  "companyName": "name of the company",
  "KBIS": "kbis value",
  "firstName": "john",
  "lastName": "max@test.fr",
  "email": "john@email.com",
  "address": "12 rue somewhere",
  "phone": "0788565289",
  "confirmationUrl": "confirmation url",
  "cancellationUrl": " cancelation url",
  "currency": "euro",
  "notificationUrl": "notification url"
}


###
PUT http://localhost:3000/merchants/3
Content-Type: application/json

{
  "currency": "$",
  "description": "Change currency"
}


###
DELETE http://localhost:3000/merchants/1


### Credentials requests
###
GET http://localhost:3000/credentials/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4

###
POST http://localhost:3000/credentials/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwiaWF0IjoxNjM5NDc5MDE4fQ.r3zAAAk2yhlTNvOl7WMILxwfOYHmYtpIBA2Ft2atrg4

{
  "clientToken": "the token ",
  "clientSecret": "shhhhh ;)"
}


###
PUT http://localhost:3000/credentials/3
Content-Type: application/json

{
  "clientToken": "the token ",
  "clientSecret": "shhhhh ;)"
}


###
DELETE http://localhost:3000/credentials/1

# History requests
###

GET http://localhost:3000/history/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU


###

GET http://localhost:3000/history/1

###

POST http://localhost:3000/history
Content-Type: application/json

{
  "transaction_id": 1,
  "status": "created",
  "date": "2021-11-17T08:26:53"
}

###

DELETE http://localhost:3000/history/1

# Operation requests

###
GET http://localhost:3000/operation/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU


###
GET http://localhost:3000/operation/35

###
POST http://localhost:3000/operation
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU

{
  "type": "CAPTURED",
  "amount": 10,
  "status": "CREATED",
  "date": "2021-11-17T08:26:53",
  "transactionId": 2
}

###
DELETE http://localhost:3000/operation/1


###
PUT http://localhost:3000/operation/31
Content-Type: application/json

{
  "status":"PENDING"
}

### User requests

### User All
### User : only same MarchandId
### Admin : All
GET http://localhost:3000/user/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU


### User All
### User : only UserId
### Admin : All
GET http://localhost:3000/user/1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU


### User All
### User : Not Access
### Admin : Access
POST http://localhost:3000/user
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDRAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6MSwiaWF0IjoxNjM5NDkxMTQ4fQ.qGXdMDjsBHLNqex82HRePewZcrf2DTEvAJkJTAHPEHU

{
  "email": "test@gmail.com",
  "password": "test",
  "firstName": "test",
  "lastName": "tt",
  "merchantId":"2"
}


###
DELETE http://localhost:3000/user/1

###
PUT http://localhost:3000/user/1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heDNAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoibWF4IiwibWVyY2hhbnRJZCI6bnVsbCwiaWF0IjoxNjM5NDkwOTIwfQ.s7wHgKixcgK31kIoDEqaUQndfNU7wlTjJ0-WUHM3MBI


{
  "merchantId":"1"
}

